/* GENERATED by build/academy/build-academy.mjs — do not edit by hand. */
window.ACADEMY_CONFIG = {
 "contactEmail": "hello@deploytlv.com",
 "enrollment": {
  "strategy": "supabase",
  "supabase": {
   "url": "https://uzloavbzhebsoizkxheb.supabase.co",
   "table": "academy_requests",
   "anonKey": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6bG9hdmJ6aGVic29pemt4aGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NDEyNjAsImV4cCI6MjA5OTAxNzI2MH0.J0Aa8FYCVQYUddvDEbeN_0yNYweYs_nupsQu1MLLlnk"
  },
  "endpoint": "",
  "fallbackFormUrl": ""
 },
 "paymentConfigured": false,
 "urls": {
  "registration": "",
  "payment": "",
  "waitlist": "",
  "confirmation": "/academy/confirmed/",
  "whatsappClass": "",
  "whatsappCommunity": "https://chat.whatsapp.com/EeSySjLJKEc6JIeus3u6sU",
  "teamsContact": ""
 },
 "cohort": {
  "date": null,
  "startTime": null,
  "endTime": null,
  "timezone": "Asia/Jerusalem",
  "dateLabel": null,
  "timeLabel": null
 },
 "venue": {
  "name": "Deploy TLV",
  "street": "Pinsker St 11",
  "locality": "Tel Aviv-Yafo",
  "postalCode": "6259413",
  "country": "IL",
  "mapUrl": "https://www.google.com/maps/search/?api=1&query=Pinsker%20St%2011%2C%20Tel%20Aviv-Yafo%2C%206259413",
  "line": "Pinsker St 11, Tel Aviv-Yafo"
 },
 "defaultCourse": "ACADEMY 101 — Build & ship a website with AI",
 "courses": [
  {
   "id": "academy-101",
   "label": "ACADEMY 101 — Build & ship a website with AI",
   "status": "waitlist"
  },
  {
   "id": "academy-102",
   "label": "ACADEMY 102 — Edit video with AI",
   "status": "waitlist"
  },
  {
   "id": "academy-103",
   "label": "ACADEMY 103 — Automate your work",
   "status": "waitlist"
  },
  {
   "id": "academy-104",
   "label": "ACADEMY 104 — Build an AI tool",
   "status": "soon"
  }
 ]
}
