/* Deploy #2 — Returning Deploy #1 alumni, matchmaking, clusters */
window.D2 = window.D2 || {};

window.D2.alumni = [
{
  id: 54, d1: true, name: "Myron Shneider", project: "Deploy TLV · Clipmatic",
  tagline: "Founder/organizer · Aleph · short-form media",
  photo: "../1/photos/Myron_Shneider.jpg", website: "clipmatic.ai", linkedin: "mshneider",
  stack: ["Claude", "Codex"], revenue: "Pre-Revenue",
  seeking: "Co-founders, being around other people building", showcasing: false,
  cluster: ["Creator / Media / Audio", "Community / VC Connectors"],
  insight: `Founded and runs Deploy TLV — the event everyone in this room is attending. AI Builder/Producer embedded at Aleph VC, viral content background (100M+ brand impressions at Doing Things Media), IDF combat veteran featured in the Jerusalem Post, and 20+ AI products shipped in the last year. He is not just a builder — he is the infrastructure.`,
  building: null,
  bg: `Northeastern University, B.S. New Venture Management. Brand Partnerships at Doing Things Media (Mar 2022–Mar 2023) — McDonald's, iRobot, Duolingo, part of the 'Corn Kid' viral moment (100M+ impressions). Social Strategy at Flock Freight. IDF Combat Reserves (Oct 2023–May 2025, featured in Jerusalem Post). AI Builder/Producer at Aleph VC (May 2025–present), producer of 'Invested by Aleph' podcast with Michael Eisenberg. Also builds Parsha Map and Diaspora Map (Jewish-community consumer products).`,
  collab: []
},
{
  id: 55, d1: true, name: "David Mekibel", project: "Balancē Creative",
  tagline: "AI-Native Visual Production",
  photo: "../1/photos/David_Mekibel.jpg", website: null, linkedin: "david-mekibel",
  stack: ["Claude", "Midjourney v8.1", "ChatGPT Image 2", "Seedance 2.0", "Higgsfield", "ComfyUI"], revenue: "Pre-Revenue",
  seeking: "Sharing", showcasing: true,
  cluster: ["Creator / Media / Audio"],
  insight: `The only attendee with deep production-grade AI visual expertise AND paying enterprise clients (Ozon Fresh, Dota 2, IRI). He is the creative/visual layer that any consumer or marketing app in the room needs.`,
  building: null,
  bg: `Emerson College (2014–2018). Co-founder & AI Video Specialist, Balancē Creative (Jan 2019–present). Russian-speaking; based in Tel Aviv. Major enterprise clients include Ozon Fresh, Nature Siberica, Winline, Dota 2, Critical Ops, IRI. Recently shipped 'The Monk Who Melted Snows' — animated short with custom moodboard-trained MJ profile.`,
  collab: []
},
{
  id: 56, d1: true, name: "Drew Stone", project: "Tangle Network",
  tagline: "Agent Optimization Infrastructure",
  photo: "photos/Drew_Stone.jpg", website: null, linkedin: "drewcstone",
  stack: ["Claude", "Codex", "OpenCode", "Cursor"], revenue: "Pre-Revenue",
  seeking: "Meeting people", showcasing: true,
  cluster: ["Agentic Dev Tools"],
  insight: `Senior infra/protocol builder with academic ML credibility. One of the rare crypto veterans making a clean, credible pivot to AI agent infrastructure rather than just rebadging a blockchain project.`,
  building: null,
  bg: `UPenn BSE (Networked & Social Systems) + MA Mathematics. Founder of Commonwealth Labs (2018–2021), Edgeware blockchain (mainnet + lockdrop, 2019–2021), and Tangle Network (Sep 2021–present). ML Research Intern at MANA Partners under Prof. Michael Kearns (algorithmic trading). Volunteer Data Scientist, Human Rights Foundation. Based partly in Tel Aviv.`,
  collab: []
},
{
  id: 57, d1: true, name: "Ari Eliezrie", project: "RadfixAI · Radware LLM Firewall",
  tagline: "LLM Security Architecture",
  photo: "../1/photos/Ari_Eliezrie.jpg", website: null, linkedin: "ari-eliezrie",
  stack: ["Claude"], revenue: "N/A",
  seeking: "Connecting", showcasing: false,
  cluster: ["AI Security & Governance"],
  insight: `An undergraduate physics student who shipped the core logic of a publicly-released enterprise LLM security product and was named internal MVP at a publicly-traded cybersecurity company. Exceptional for someone in their junior year of college.`,
  building: null,
  bg: `Physics student, Columbia University (2023–2027). Based in Los Angeles. R&D role in the CTO's Office at Radware (NASDAQ: RDWR). Named Radware MVP 2024. Led development of the core logic for Radware's LLM Firewall (launched Nov 2025) — monitors and blocks prompt injection, jailbreaks, and GenAI exploits. RadfixAI: his stealth side project, likely an AI-powered vulnerability remediation or LLM security tool.`,
  collab: []
},
{
  id: 58, d1: true, name: "Michael Heiser", project: "Newhedge · LIT Ai",
  tagline: "Web3 + Bitcoin Analytics + AI Trading",
  photo: "../1/photos/Michael_Heiser.jpg", website: null, linkedin: "michael-heiser-dev",
  stack: ["Cursor"], revenue: "N/A",
  seeking: "Connecting", showcasing: false,
  cluster: ["Crypto / Web3"],
  insight: `The rare combination of deep web3 technical execution (Solidity, NFT platforms, $500K+ in sales) + Bitcoin analytics (Newhedge) + AI trading systems (LIT Ai) makes him a unique intersection of web3, AI, and fintech.`,
  building: null,
  bg: `CS certification, UCLA Extension coding bootcamp (2018). Built a platform generating $500K+ in NFT sales on Ethereum. Co-founder and CTO of Vault 721 (DeFi/NFT protocol). Separate identity as 'LIT Ai (Language Interface Trading)' — AI-driven crypto trading tools. Megga Ventures = his holding/investment vehicle. Now in the Newhedge orbit as advisor, investor, or technical collaborator.`,
  collab: []
},
{
  id: 59, d1: true, name: "Shimon Rosen", project: "PodSnacks",
  tagline: "AI Podcast Summarization + Daily News Podcast",
  photo: "../1/photos/Shimon_Rosen.jpg", website: "podsnacks.com", linkedin: "shimondotcom",
  stack: ["Claude"], revenue: "Revenue",
  seeking: "Connecting and collaborating", showcasing: false,
  cluster: ["Creator / Media / Audio", "Consumer / Indie Builders"],
  insight: `Fast Company mention + serial founder track record + HN traction = externally validated media AI product with real distribution. He understands the content-to-audience flywheel from multiple angles.`,
  building: null,
  bg: `Serial startup founder. Prior: SpeakerGram (speaker booking, Mixergy coverage), MakeSpace, Scaffold. PodSnacks (podsnacks.com) — AI-powered podcast summarization delivering summaries by email ($1/hour of podcast content), PLUS a daily news roundup podcast on Apple/Spotify/YouTube. Listed by Fast Company as among the best AI podcast summary tools in 2026.`,
  collab: []
},
{
  id: 60, d1: true, name: "Sam Weinstein", project: "White City AI · Lunchbox Legends",
  tagline: "AI consulting & AI trading cards for kids",
  photo: "../1/photos/Sam_Weinstein.jpg", website: null, linkedin: "sam-weinstein-b202b658",
  stack: ["Claude"], revenue: "Revenue",
  seeking: "Meeting others, learning, sharing", showcasing: false,
  cluster: ["Consumer / Indie Builders", "Hardware / Manufacturing"],
  insight: `Lunchbox Legends is a genuinely differentiated consumer product — the emotional hook (your child as a superhero) is strong, the physical form factor commands a premium price, and gift/occasion virality is built in. 7.5 years in enterprise SaaS customer success gives him a GTM playbook most consumer builders lack.`,
  building: null,
  bg: `Reichman University (IDC Herzliya). ~7.5 years at Litify (Salesforce-native legal operating platform, Associate Director of Customer Success). Relocated to Israel and launched White City AI (AI automation consulting) in early 2024. Lunchbox Legends: parents upload photos of children → receive 25 custom AI-generated trading cards mailed to them.`,
  collab: []
},
{
  id: 61, d1: true, name: "Ilan Oz", project: "EmberNovels",
  tagline: "Custom AI Romance Novels",
  photo: "../1/photos/Ilan_Oz.jpg", website: null, linkedin: "ilan-oz-36520464",
  stack: ["Claude", "Codex"], revenue: "Revenue",
  seeking: "Being around other builders facing the same challenges", showcasing: false,
  cluster: ["Consumer / Indie Builders"],
  insight: `Has proven B2C generative content can convert to consistent revenue ($5–10K/mo) while operating inside one of Israel's most sophisticated AI/security ecosystems. The most instructive 'how to actually ship and earn' story in the room for pre-revenue founders.`,
  building: null,
  bg: `TAU Coller MBA; UW-Madison BA Economics. Business Development Manager at Team8 (Mar 2025–present) — one of Israel's premier cybersecurity/AI foundries. Prior: Atera (2yrs), anecdotes (1.5yrs), monday.com (10mo), Google Ireland (2yrs).`,
  collab: []
},
{
  id: 62, d1: true, name: "Artem Belyakov", project: "Medida",
  tagline: "Computer Vision for Home Renovation Measurements",
  photo: "../1/photos/Artem.jpg", website: null, linkedin: "belyakov-am",
  stack: ["Claude", "Codex", "OpenCode"], revenue: "N/A",
  seeking: "Good people + knowledge sharing; open to consulting", showcasing: false,
  cluster: ["Deep Tech / Research / Clinical AI"],
  insight: `Yandex School of Data Analysis + $3M ARR at one year old (Angular Ventures-backed) = elite ML foundation meets proven shipping velocity. One of the strongest technical profiles in the room.`,
  building: null,
  bg: `B.Sc. Computer Science, Higher School of Economics (HSE), Moscow. External student at Yandex School of Data Analysis. Prior: SberDevices, SmartDec (smart contract security), Minimax.Finance (DeFi), X5 Group. Founding Member at Medida (Tel Aviv) — smartphone scan → millimeter-accurate home renovation measurements. $4M seed from Angular Ventures. $3M ARR in 35 US states after one year.`,
  collab: []
},
{
  id: 63, d1: true, name: "Guillaume Bensoussan", project: "Mai Boyar School CRM",
  tagline: "AI School Admin Portal + Personal Second Brain",
  photo: "../1/photos/Guillaume_Bensoussan.jpg", website: "portail-boyar.web.app", linkedin: "guillaume-bensoussan",
  stack: ["Claude", "Codex", "Cursor"], revenue: "Revenue",
  seeking: "Connecting with AI builders, learning about agents", showcasing: false,
  cluster: ["Enterprise / Internal AI", "Consumer / Indie Builders"],
  insight: `Shipped a working Firebase web app for a real institution (Mai Boyar School) with an AI-powered teacher replacement module — deployed, not a prototype. The buyer-builder hybrid: identifies a real institutional pain point and builds the solution himself.`,
  building: null,
  bg: `French-Israeli. Working at or with Mai Boyar School — a prestigious Israeli boarding school with IB program and 1,000+ students. Built a Firebase-hosted school management portal (portail-boyar.web.app). Also built his own AI 'second brain' using Obsidian + Graphify + Claude/Codex.`,
  collab: []
},
{
  id: 64, d1: true, name: "Daniel Conway", project: "Proofed",
  tagline: "Attribution & deal platform for restaurants + creators",
  photo: "../1/photos/Daniel_Conway.jpg", website: "tryproofed.app", linkedin: "danielpconway",
  stack: ["Claude"], revenue: "Pre-Revenue",
  seeking: "Feedback, collaborators, tips & workflows", showcasing: false,
  cluster: ["Creator / Media / Audio", "AI Visibility / Search / Marketing"],
  insight: `The attribution problem he is solving is legitimate and underserved. Most restaurant-influencer platforms handle matching but not attribution. His content strategy background and food industry network are genuine distribution advantages.`,
  building: null,
  bg: `B.S. Environmental Economics & Policy, UC Berkeley. Founded Plant Futures Berkeley Chapter, collaborated with Beyond Meat on a campus ambassador program. Content Strategist at PikMe. Proofed (tryproofed.app) — connects restaurants with food influencers, closing the attribution loop from creator post to restaurant revenue.`,
  collab: []
},
{
  id: 65, d1: true, name: "Fedorov Dmitrii", project: "SinsingRisk",
  tagline: "UAV + CV Disaster Response Platform",
  photo: "../1/photos/Fedorov_Dmitrii.jpg", website: null, linkedin: "dmitriifedorov",
  stack: ["Claude"], revenue: "Pre-Revenue",
  seeking: "Partners and builders in the space", showcasing: false,
  cluster: ["Defense / Dual-Use", "Deep Tech / Research / Clinical AI"],
  insight: `Architectural Association Design&Make alumni are among the most technically sophisticated computational architects in the world. Fedorov brings 11 years of real infrastructure experience to a CV/UAV disaster response product.`,
  building: null,
  bg: `MArch + MSc from the Architectural Association (AA) London — Design&Make studio. Educator Architect at AA School. Project Architect at OOO studio, St Petersburg (11 years — airports, palaces). Expert in Rhino/Grasshopper, robotic fabrication (KUKA). SinsingRisk: UAV + computer vision platform for disaster response, producing structured damage attribution of the built environment.`,
  collab: []
},
{
  id: 66, d1: true, name: "Vlad Neyshtadt", project: "AVA Atelier + Studio Automation",
  tagline: "Self-Portrait Studio + Automation Tools",
  photo: null, website: "anivea.com", linkedin: "vneyshyadt",
  stack: ["Claude"], revenue: "$5,000–$10,000/month",
  seeking: "Connecting, sharing expertise, feedback", showcasing: false,
  cluster: ["Revenue Leaders", "Creator / Media / Audio"],
  insight: `Simultaneously running a revenue-generating physical business ($5–10K/mo) AND building software tools to automate it — the purest form of 'scratch your own itch' product development.`,
  building: null,
  bg: `Runs AVA Self-Photography Atelier (anivea.com) — a self-portrait studio at Ben Yehuda 94, Tel Aviv. Camera hidden behind a mirror; client photographs themselves with a remote button. Revenue: $5K–$10K/month. Building automations and a separate web app for studio operations using Claude.`,
  collab: []
},
{
  id: 67, d1: true, name: "Moshe Schlussel", project: "TheraTrain AI",
  tagline: "AI Simulation Platform for Therapist Training",
  photo: "photos/Moshe_Schlussel.jpg", website: "theratrainai.com", linkedin: "moshe-schlussel-5b87441ab",
  stack: ["Claude", "Codex", "OpenCode"], revenue: "Pre-Revenue",
  seeking: "Co-founder, sharing, feedback", showcasing: true,
  cluster: ["Health, Wellness & Bio-AI"],
  insight: `Building in an academically validated category at exactly the right time — therapist training is a multi-billion dollar market with structural inefficiencies. His outsider status requires a clinical co-founder, but the timing and concept are strong.`,
  building: null,
  bg: `Solar Consultant at Flex Power (day job) — an outsider building a training platform for therapists. TheraTrain AI (theratrainai.com) — AI simulation of therapy clients that therapists can practice on: AI clients that 'never judge, never break character, and never run out of patience.' Category validated by Stanford HAI and academic research.`,
  collab: []
},
{
  id: 68, d1: true, name: "Menachem Berrebi", project: "Renaissance ML",
  tagline: "AI Design to Physical Product",
  photo: "../1/photos/Mendy_Berrebi.jpg", website: null, linkedin: "mendy-berrebi",
  stack: ["Claude", "Cursor"], revenue: "Pre-Revenue",
  seeking: "Finding co-founders and collaborators", showcasing: false,
  cluster: ["Co-founder Actively Seeking", "Hardware / Manufacturing"],
  insight: `The Renaissance ML concept — AI-generated design to physical manufactured product — is genuinely novel with large potential. His commercial sales background (Applitools, Unleash) means he can sell — he needs a technical partner.`,
  building: null,
  bg: `Reichman University (IDC Herzliya). Career: Lightchain Labs (blockchain) → Applitools (Enterprise AE) → Unleash (AE) → Renaissance ML (Co-Founder). Runs Edeneum Substack — philosophical essays. Renaissance ML: AI-generated images / design descriptions → physical manufactured products. Current focus: jewelry in precious metals.`,
  collab: []
},
{
  id: 69, d1: true, name: "Benjamin Lieber", project: "OriginAI · cowriter.com",
  tagline: "Applied AI research & AI writing tools",
  photo: null, website: "cowriter.com", linkedin: null,
  stack: ["Claude", "Cursor"], revenue: "N/A",
  seeking: "Meet and learn", showcasing: false,
  cluster: ["Deep Tech / Research / Clinical AI"],
  insight: `If affiliated with OriginAI (Elbit/NVIDIA/Axon Vision), he has access to defense-grade applied ML infrastructure — a rare foundational advantage. His 'meet and learn' posture means he is in absorb mode and open to any direction.`,
  building: `An AI writing/content product (cowriter.com) leveraging NLP/LLM capabilities, built while embedded in Israel's serious applied-AI ecosystem.`,
  bg: `Affiliated with OriginAI in Israel — an applied AI research center (Ramat-Gan) involving Elbit Systems, Axon Vision, and NVIDIA, focused on vision, speech, NLP, and ML. The cowriter.com domain suggests an AI writing product.`,
  collab: [
    `Yaacov Albietz & Daniel Benzaquen Moreno — LLM / NLP product peers.`,
    `Artem Belyakov & Max Matkovski — Applied-ML engineers.`,
    `Akiva Lipshitz — Deep-tech research.`
  ]
},
{
  id: 70, d1: true, name: "Omer Geva", project: "Boundly",
  tagline: "Private second-home sharing platform",
  photo: "../1/photos/Omer_Geva.jpg", website: "boundly.app", linkedin: "omergeva",
  stack: ["Claude"], revenue: "Pre-Revenue",
  seeking: "—", showcasing: false,
  cluster: ["Consumer / Indie Builders"],
  insight: `A differentiated niche in short-term rentals — the 'private/trusted' angle fills a real gap between informal key-lending and full Airbnb listing, and as a full-stack team lead he can build it himself.`,
  building: `Boundly (boundly.app) — a private second-home sharing platform for owners to manage stays with trusted people (family, friends): automates guest comms, syncs Airbnb/VRBO calendars, sets per-guest pricing. Differentiates on the trusted-circle dimension. Pre-revenue.`,
  bg: `Reichman University. Experienced full-stack developer (Express.js, Node.js, SQL) with engineering team-lead experience; previously listed a stealth AI startup before pivoting to Boundly.`,
  collab: [
    `Arielle Aboav (HomieSwap) — CRITICAL: both home-sharing/travel consumer apps; the most direct domain peer in the room.`,
    `Samuel Green (Guesty) — Short-term-rental / proptech crossover.`,
    `Artem Belyakov (Medida) — PropTech / built-environment.`
  ]
},
{
  id: 71, d1: true, name: "Alon Shvartsman", project: "Newhedge",
  tagline: "Bitcoin intelligence platform ('Bloomberg Terminal for Bitcoin')",
  photo: "../1/photos/Alon_Shvartsman.jpg", website: "newhedge.io", linkedin: "alonshvartsman",
  stack: ["Codex"], revenue: "$5,000–$10,000/month",
  seeking: "New people", showcasing: false,
  cluster: ["Crypto / Web3", "Fintech / Finance", "Revenue Leaders"],
  insight: `The Bitcoin Data API launch signals Newhedge evolving from dashboard into data infrastructure — a much larger B2B opportunity; 12 institutional clients on $400K raised is strong unit economics for a bootstrapped Israeli analytics company.`,
  building: `Newhedge aggregates on-chain data, analytics, live order books, and derivatives data from 15+ exchanges (~2,000 users, 12 institutional clients; $400K raised from Fusion VC + HashKey). In March 2026 launched a public Bitcoin Data API (MVRV, Realized Price, SOPR, HODL Waves, hashrate) — a pivot from dashboard to B2B data infrastructure.`,
  bg: `Prior: DeepUI Engineer at WalkMe → developer at LiquidApps → founder of Bitrawr (Bitcoin education). Co-founded Newhedge with Omri Shabtay (CTO) and Mert Gunduz (Lead Engineer).`,
  collab: [
    `Michael Heiser (LIT Ai · D#1) — Already collaborating; Bitcoin analytics + AI trading.`,
    `Marissa Posner (Ethereum) & Noam Cohen (Spikeet) — Crypto / markets-data peers.`,
    `Doron Haberer (LovedByAI) — GEO so 'best Bitcoin analytics platform' surfaces Newhedge in AI search.`,
    `Amitay Manor (Aleph) — Warm path into a fund if Newhedge is raising.`
  ]
}
];

window.D2.matches = [
{ rank: 1, a: "Doron Haberer", b: "Zohar Mosseri", tag: "COLLABORATION", why: `Both operate on how brands are perceived by machines and the public — Doron wins citations in AI answers (GEO), Zohar monitors narratives and crises. Complementary, and both already revenue-generating.` },
{ rank: 2, a: "Gil G", b: "Ari Eliezrie", tag: "CRITICAL", why: `Adjacent LLM-security/governance layers. Ari built the LLM prompt firewall (Radware); Gil builds the prompt/tool governance gateway. Compare architectures.` },
{ rank: 3, a: "Noam Cohen", b: "Yaacov Albietz", tag: "PRODUCT PARTNERSHIP", why: `Spikeet's historical financial data is exactly the data layer an AI-native investment advisor needs. Direct product synergy.` },
{ rank: 4, a: "Jeff Feiereisen", b: "Sam Weinstein", tag: "MENTORSHIP", why: `Two physical-product DTC builders in an AI-software room. Jeff (ex-Amazon Go, successful Kickstarter, $10K+/mo) is the DTC operator Sam can learn the most from.` },
{ rank: 5, a: "Myron Shneider", b: "Jeff Feiereisen", tag: "COLLABORATION", why: `Myron built a physical DTC subscription company (Brushed) into Target's incubator (top 15 of 5,000) and ran e-commerce ops for a CPG brand; Jeff is an ex-Amazon Go engineer running a $10K+/mo DTC hardware business. The deepest physical-commerce exchange in the room.` },
{ rank: 6, a: "Myron Shneider", b: "Jorge Rybar", tag: "COLLABORATION", why: `Both build Jewish-community consumer products — Myron's Parsha Map and Diaspora Map alongside Jorge's Give10 Maaser/Tzedakah tracker. Direct domain overlap.` },
{ rank: 7, a: "Myron Shneider", b: "Doron Haberer", tag: "REVENUE", why: `Deploy TLV and Clipmatic need to surface in AI search; Doron's GEO plugin is the exact channel. Myron's Aleph distribution reach makes him a high-value design partner in return.` },
{ rank: 8, a: "Myron Shneider", b: "Samuel Green", tag: "COLLABORATION", why: `Myron produces three Aleph podcasts and built PodcastPal (broadcast-quality remote recording); Samuel built a podcast site with automations. Podcast/media operators.` },
{ rank: 9, a: "David Mekibel", b: "Alon Bronfeld", tag: "PRODUCT PARTNERSHIP", why: `Bronfelds Hub is built on founder-investor video; David runs a production-grade AI visual/video pipeline with paying enterprise clients. Natural production partnership and feedback.` },
{ rank: 10, a: "David Mekibel", b: "Lior Kupfer", tag: "TECHNICAL", why: `Both build AI video-production pipelines for creators — David for enterprise brand visuals, Lior for guitarist content. Adjacent pipelines, technical exchange.` },
{ rank: 11, a: "David Mekibel", b: "Ishai Waisman", tag: "COLLABORATION", why: `AI body-language/storytelling coaching meets production-grade AI visual production — complementary halves of the on-camera presentation stack.` },
{ rank: 12, a: "Myron Shneider", b: "David Mekibel", tag: "COLLABORATION", why: `Both AI-first visual/content producers — Myron on distribution short-form and Aleph media, David on enterprise brand visuals. Complementary production strengths.` },
{ rank: 13, a: "Avi Amoyal", b: "Drew Stone", tag: "PRODUCT PARTNERSHIP", why: `Agent application (voice-to-PR) meets agent-optimization infrastructure. Classic infra-meets-app pairing.` },
{ rank: 14, a: "Marissa Posner", b: "Liron Achdut", tag: "SECURITY", why: `Marissa builds Ethereum payment rails for AI agents; Liron audits smart-contract risk with AI. Security review for agent micropayments is the natural collaboration.` },
{ rank: 15, a: "Han Rabinovitz", b: "Danya Dotan", tag: "CHEMISTRY", why: `Both argue the missing piece is the human layer of AI adoption. Shared thesis, complementary framings (leadership strategy vs. interaction infrastructure).` },
{ rank: 16, a: "Martin Miller", b: "Gil G", tag: "TECHNICAL", why: `Two GenAI-security builders. Lasso's LLM-protection depth and Gil's governance-gateway approach are highly comparable — peer exchange on guardrails.` },
{ rank: 17, a: "Coral Fussman", b: "Alon Bronfeld", tag: "COLLABORATION", why: `Both build AI-native deal/discovery platforms (deal execution vs. founder-investor matching). Adjacent GTM tooling — natural product conversation.` },
{ rank: 18, a: "Amitay Manor", b: "Ben Barak", tag: "TECHNICAL", why: `Two builders shipping internal AI agents at well-known companies (a $850M fund vs. a public work-OS). Compare agent architectures and ops automation.` },
{ rank: 19, a: "Alon Bronfeld", b: "Amitay Manor", tag: "FUNDING", why: `Aleph is precisely the kind of investor Bronfelds Hub is built for. Direct user feedback — and a possible route into a top fund.` },
{ rank: 20, a: "Ishai Waisman", b: "Han Rabinovitz", tag: "COLLABORATION", why: `Both work on human communication and presence. Ish-AI productizes coaching; Han advises on AI-era communication strategy. Natural peers.` },
{ rank: 21, a: "Akiva Lipshitz", b: "Daniel Benzaquen Moreno", tag: "TECHNICAL", why: `The two deepest technical minds in the new cohort: statistical-physics-for-ML research meets 7 years of applied LLM engineering. High-signal exchange.` },
{ rank: 22, a: "Lior Kupfer", b: "Shimon Rosen", tag: "COLLABORATION", why: `Both build AI media/audio creator tooling. Tabbers turns guitar video into lessons; PodSnacks turns podcasts into clips — adjacent pipelines.` },
{ rank: 23, a: "Shay Zaltsman", b: "Jeff Feiereisen", tag: "TECHNICAL", why: `The two hardware-leaning attendees. Affordable Israeli manufacturing meets a proven DTC hardware operator — practical supply-chain exchange.` },
{ rank: 24, a: "Matan Harsat", b: "Yaacov Albietz", tag: "CO-FOUNDER?", why: `Both AI-fluent technical builders explicitly seeking co-founders. A direct co-founder conversation.` },
{ rank: 25, a: "Daniel Benzaquen Moreno", b: "Yaacov Albietz", tag: "TECHNICAL", why: `Two LLM-application builders (AI diagramming vs. multi-LLM workspace). Technical peers on model orchestration and UX.` },
{ rank: 26, a: "Isaac Horowitz", b: "Doron Haberer", tag: "CRITICAL", why: `Both build AI-search-optimization (AEO/GEO) products — MentionWell autonomously publishes citation-tracked content; LovedByAI wins WordPress citations in AI answers. The strongest AI-search peer match in the room.` },
{ rank: 27, a: "Ben Badejo", b: "Avi Amoyal", tag: "COLLABORATION", why: `Both build voice/agentic developer interfaces — voice-to-agent vs. voice-to-PR. The deepest voice-agent exchange across the cohort.` },
{ rank: 28, a: "Daniel Raccah", b: "Isaac Horowitz", tag: "COLLABORATION", why: `Two revenue-generating AI-agency operators. Compare delivery models, productization, and how to scale fixed-bid AI builds.` },
{ rank: 29, a: "Sigal Sax", b: "Gil G", tag: "SECURITY", why: `A GenAI-security engineer (Lasso) meets an AI-governance founder. Guardrail and enforcement architecture exchange — and Martin Miller (also Lasso) completes a three-way security cluster.` },
{ rank: 30, a: "Max Matkovski", b: "Michael Salaverry", tag: "TECHNICAL", why: `Two production-grade ML/staff engineers — the senior-engineer peer exchange both came looking for.` },
{ rank: 31, a: "Ofek Seroussi", b: "Michael Salaverry", tag: "TECHNICAL", why: `AI staff engineers who each explicitly want mutual engineer-to-engineer guidance. Direct match.` },
{ rank: 32, a: "Gavriel Hannuna", b: "Akiva Lipshitz", tag: "TECHNICAL", why: `Clinical-AI / bioinformatics (QuantHealth, ETH Zürich) meets statistical-physics-for-ML research. The deepest scientific-AI pairing in the cohort.` },
{ rank: 33, a: "Adam Kohler", b: "Danya Dotan", tag: "COLLABORATION", why: `Document/knowledge-work automation: legal-template drafting meets cognitive-friction reduction for knowledge workers. Adjacent problems.` },
{ rank: 34, a: "Ilya Kogan", b: "Noam Cohen", tag: "COLLABORATION", why: `An alternative-assets / royalties analytics play needs market-data infrastructure — Spikeet is exactly that kind of data layer. Finance-data peers.` },
{ rank: 35, a: "Gabriel Gothold", b: "Jeff Feiereisen", tag: "COLLABORATION", why: `E-commerce pricing/ops at portfolio scale meets a hands-on DTC operator. Practical commerce exchange.` },
{ rank: 36, a: "Arielle Aboav", b: "Ben Barak", tag: "CHEMISTRY", why: `Colleagues at monday.com both building consumer products on the side — natural ally pairing.` },
{ rank: 37, a: "Alexander Mendelsohn", b: "Matan Harsat", tag: "CO-FOUNDER?", why: `Two strong engineers/data scientists co-founder-shopping with production pedigrees. A direct co-founder conversation.` },
{ rank: 38, a: "Eitan Engelberg", b: "Moshe Schlussel", tag: "CRITICAL", why: `Both mental-health AI — cross-border therapy delivery meets AI therapist-training. Same market from two angles.` },
{ rank: 39, a: "Louis Guthmann", b: "Adam Kohler", tag: "CRITICAL", why: `The two law-×-AI builders in the room — AI governance/compliance strategy meets hands-on legal-document automation.` },
{ rank: 40, a: "Dylan Redfield", b: "Drew Stone", tag: "PRODUCT PARTNERSHIP", why: `Agentic harnesses (the scaffolding around LLMs) meet agent-optimization infrastructure — adjacent layers of the agent stack.` },
{ rank: 41, a: "Micky Aflalo", b: "Tom Cohen", tag: "SECURITY", why: `Offensive-cyber founder meets a senior AI-security engineer — red-team perspective plus the broader Lasso/IRONSCALES security cluster.` },
{ rank: 42, a: "Alon Shvartsman", b: "Doron Haberer", tag: "REVENUE", why: `'Best Bitcoin analytics platform' should surface in AI answers; Doron's GEO product is the exact channel for Newhedge's B2B data API.` },
{ rank: 43, a: "Louis Guthmann", b: "Marissa Posner", tag: "TECHNICAL", why: `Two deep crypto/ZK technical strategists — StarkWare ecosystem meets Ethereum account-abstraction. Natural high-level peer exchange.` }
];

window.D2.clusterDefs = [
{ name: "AI Security & Governance", color: "#C2410C" },
{ name: "Crypto / Web3", color: "#7C3AED" },
{ name: "Agentic Dev Tools", color: "#2563EB" },
{ name: "Health, Wellness & Bio-AI", color: "#0D9488" },
{ name: "Law / Professional-Services AI", color: "#A16207" },
{ name: "Enterprise / Internal AI", color: "#0F766E" },
{ name: "Fintech / Finance", color: "#15803D" },
{ name: "AI Services / Agencies", color: "#C026D3" },
{ name: "Senior ML / Staff Engineers", color: "#1E40AF" },
{ name: "E-Commerce / Retail AI", color: "#EA580C" },
{ name: "Founder–Investor / Dealmaking", color: "#B45309" },
{ name: "AI Visibility / Search / Marketing", color: "#DB2777" },
{ name: "Human–AI Interface / Adoption", color: "#4F46E5" },
{ name: "Communication / Coaching", color: "#0891B2" },
{ name: "Consumer / Indie Builders", color: "#CA8A04" },
{ name: "Creator / Media / Audio", color: "#9333EA" },
{ name: "Deep Tech / Research / Clinical AI", color: "#1D4ED8" },
{ name: "Hardware / Manufacturing", color: "#B91C1C" },
{ name: "Defense / Dual-Use", color: "#4D7C0F" },
{ name: "Revenue Leaders", color: "#047857" },
{ name: "Co-founder Actively Seeking", color: "#BE123C" },
{ name: "Community / VC Connectors", color: "#7E22CE" }
];

window.D2.tagColors = {
  "CRITICAL": "#DC2626",
  "FUNDING": "#047857",
  "PRODUCT PARTNERSHIP": "#2563EB",
  "REVENUE": "#CA8A04",
  "TECHNICAL": "#4F46E5",
  "CHEMISTRY": "#DB2777",
  "SKILL MATCH": "#0891B2",
  "COLLABORATION": "#7C3AED",
  "MENTORSHIP": "#EA580C",
  "SECURITY": "#475569",
  "CO-FOUNDER?": "#BE123C"
};

window.D2.breakoutGroups = [
{ id: 1, color: "#C2410C", name: "Security, Governance & Cyber",
  focus: `Securing LLMs and agents — prompt firewalls, governance/enforcement gateways, red-teaming, and AI for the SOC.`,
  anchor: "Ari Eliezrie (Radware LLM firewall)",
  members: ["Liron Achdut", "Gil G", "Tom Cohen", "Martin Miller", "Sigal Sax", "Micky Aflalo", "Ari Eliezrie"] },
{ id: 2, color: "#2563EB", name: "Agents, Dev Tools & Infrastructure",
  focus: `The agent stack — orchestration, voice/agentic dev interfaces, multi-LLM tooling, and what infrastructure agents need underneath.`,
  anchor: "Drew Stone (Tangle)",
  members: ["Drew Stone", "Dylan Redfield", "Avi Amoyal", "Ben Badejo", "Amitay Keisar", "Yaacov Albietz", "Daniel Benzaquen Moreno", "Ofek Seroussi", "Matan Harsat"] },
{ id: 3, color: "#1E40AF", name: "Deep Tech, ML & Autonomous Systems",
  focus: `Production ML and research-to-product — RAG/agents over structured data, computer vision, autonomy/UAV, and applied research.`,
  anchor: "Max Matkovski (ex-Meta / Corvic)",
  members: ["Akiva Lipshitz", "Max Matkovski", "Yaniv Azriel", "Fedorov Dmitrii", "Benjamin Lieber"] },
{ id: 4, color: "#15803D", name: "Fintech, Crypto & Markets",
  focus: `Crypto rails and agent payments, financial/market data, alternative assets, and AI in finance ops.`,
  anchor: "Marissa Posner (Ethereum Foundation)",
  members: ["Marissa Posner", "Noam Cohen", "Coral Fussman", "Ilya Kogan", "Filipp Shilnikov", "Alexander Mendelsohn", "Alon Shvartsman", "Michael Heiser"] },
{ id: 5, color: "#9333EA", name: "Consumer, Creator & Media",
  focus: `Consumer AI, creator and media tooling, visual production, and distribution — turning AI output into audience.`,
  anchor: "Shimon Rosen / Myron Shneider",
  members: ["Lior Kupfer", "Jorge Rybar", "Samuel Green", "Arielle Aboav", "Daniel Warren", "Matan Porat", "Shimon Rosen", "David Mekibel", "Ilan Oz", "Vlad Neyshtadt"] },
{ id: 6, color: "#C026D3", name: "AI Services, Agencies, GTM & AI-Search",
  focus: `Delivering AI as a service — agency/studio models, AEO/GEO (getting cited by AI), GTM engineering, and content/narrative.`,
  anchor: "Isaac Horowitz (ZipLyne)",
  members: ["Daniel Raccah", "Isaac Horowitz", "Grigory Tal", "Doron Haberer", "Zohar Mosseri", "Jonathan Harel", "Han Rabinovitz", "Sara Spagnoletto", "Daniel Conway"] },
{ id: 7, color: "#0F766E", name: "Enterprise, Internal AI, Productivity & Capital",
  focus: `AI inside organizations — internal agents, knowledge-work and productivity, education, legal/doc automation, and the founder–investor interface.`,
  anchor: "Amitay Manor / Myron Shneider",
  members: ["Amitay Manor", "Ben Barak", "Danya Dotan", "Adam Kohler", "Louis Guthmann", "Alon Bronfeld", "Menachem Berrebi", "Guillaume Bensoussan", "Myron Shneider"] },
{ id: 8, color: "#B91C1C", name: "Hardware, PropTech, Commerce & Physical",
  focus: `Where AI meets the physical world — hardware/DTC, manufacturing, robotics/UAV, proptech/rentals, and e-commerce ops.`,
  anchor: "Jeff Feiereisen / Sam Weinstein",
  members: ["Jeff Feiereisen", "Shay Zaltsman", "Gabriel Gothold", "Ike Bodner", "Michaël Weizmann", "Omer Geva", "Artem Belyakov", "Sam Weinstein"] },
{ id: 9, color: "#DB2777", name: "Health, Wellness & Bio-AI",
  focus: `Clinical, bio, and wellness AI — therapist training, drug-safety/clinical simulation, femtech, and communication/coaching.`,
  anchor: "Moshe Schlussel (TheraTrain)",
  members: ["Moshe Schlussel", "Eitan Engelberg", "Alex Schajer", "Ishai Waisman", "Gavriel Hannuna", "Michael Salaverry"] }
];
